Makefile
README.md
docs/openapi/v1.yml
internal/handler/oapi/oapi_models.go

- :sparkles: add go-gen command
- :adhesive_bandage: change WsResponseType's type from object to string

WsResponseTypeがstringではなくobjectになってた

---

docs/openapi/v1.yml
internal/handler/oapi/oapi_models.go

- :memo: add openapi description
- :memo: add WsRequest.Body description
- :memo: add comment to props
- :recycle: split Card info

openapiを見やすくした

---

go.mod
go.sum
integration/ws/ws_test.go
internal/usecases/services/ws/client.go
internal/usecases/services/ws/hub.go
internal/usecases/services/ws/streamer.go
main.go
pkg/log/log.go

- :boom: change logger to zap
- :recycle: keep running as long as possible

loggerをechoからzapに変更する

---

internal/usecases/services/ws/client.go
main.go
pkg/config/config.go
pkg/log/log.go

- :recycle: manage config by flag
- :wrench: change logger when devmode

環境変数をflagで管理

---

internal/usecases/services/ws/client.go

:adhesive_bandage: dont close conn in readpump

---

integration/ws/ws_test.go
internal/domain/card.go
internal/oapi/converter.go
internal/usecases/repository/card.go
internal/usecases/repository/repoimpl/card.go
internal/usecases/services/ws/client.go
internal/usecases/services/ws/hub.go
internal/usecases/services/ws/wshandler/gamestart.go
internal/usecases/services/ws/wshandler/wshandler.go
main.go

- :sparkles: add empty cardRepo
- :sparkles: impl drawcard for test

cardRepositoryのひな型

---

docs/openapi/v1.yml
integration/ws/ws_test.go
internal/handler/handler.go
internal/oapi/converter.go
internal/oapi/oapi_models.go
internal/usecases/services/ws/client.go
internal/usecases/services/ws/hub.go
internal/usecases/services/ws/streamer.go

- :boom: userID -> playerID
- :boom: Player.PlayerId -> Player.Id
- :boom: Room.RoomId -> Room.Id

change id name

---

docs/openapi/v1.yml
internal/domain/room.go
internal/handler/handler.go
internal/oapi/converter.go
internal/oapi/oapi_models.go

- https://github.com/hackathon-22-winter-01/hackathon-22-winter-01_backend/pull/34/files#r1050415785

🐛 impl RoomFromDomain

---

internal/usecases/services/ws/wshandler/card.go

✨ impl CardTypeGalaxyBrain

---

docs/openapi/v1.yml
internal/handler/handler.go
internal/oapi/oapi_models.go
internal/oapi/oapi_server.go

close #59
- :boom: playerIdをparamで持つ
- :boom: change room response

playerIdをGET /wsのqueryに持たせる

---

docs/openapi/v1.yml
integration/ws/ws_test.go
internal/domain/lifeevent.go
internal/oapi/constructor.go
internal/oapi/converter.go
internal/oapi/oapi_models.go
internal/usecases/services/ws/wshandler/life.go
pkg/consts/consts.go

- :boom: change maxLife 3 -> 100.0
- :boom: remove decrement & impl damaged and healed

体力をfloatで持ち減少、回復を実装

---

internal/domain/card.go
internal/usecases/services/ws/wshandler/card.go

- :memo: add CardType comment
- :memo: add todo

add CardEvent comment

---

docs/openapi/v1.yml
integration/ws/ws_test.go
internal/oapi/oapi_models.go
internal/usecases/services/ws/wshandler/gamestart.go

- close #60 
- ルームに一番最初に参加人だけスタートできるようにした。
- ルームの人数が2よりも少ない場合は、スタートできないようにした。

👔　人数確認、room に最初に追加されたプレイヤーのみ開始できる。

---

internal/domain/event.go
internal/domain/player.go
internal/usecases/services/ws/wshandler/card.go

- :sparkles: impl JustCardEvent
- :recycle: at first, define cardType

impl justcardevent

---

docs/openapi/v1.yml
internal/domain/card.go
internal/domain/event.go
internal/domain/rail.go
internal/oapi/constructor.go
internal/oapi/converter.go
internal/oapi/oapi_models.go
internal/usecases/services/ws/client.go
internal/usecases/services/ws/wshandler/block.go
internal/usecases/services/ws/wshandler/card.go

- Delete HasBlock
- Fix time.Now() => jst.Now()
- 障害物のロジックを実装
- close #9

✨ 障害物のロジック

---

internal/usecases/services/ws/wshandler/card.go

- Open Sourcerer の回復力を 30 から 全回復に変更
- close #70

Open Sourcerer の回復力を 30 から 全回復に変更

---

internal/domain/event.go
internal/usecases/services/ws/wshandler/block.go
internal/usecases/services/ws/wshandler/card.go

:fire: remove TargetId

---

docs/openapi/v1.yml
internal/domain/card.go
internal/oapi/oapi_models.go
internal/usecases/services/ws/wshandler/card.go

✨ impl ZeroDay

---

go.mod
go.sum
integration/ws/testutils_test.go
integration/ws/ws_test.go
internal/oapi/converter.go
internal/oapi/testutils.go
internal/usecases/services/ws/wshandler/card.go
pkg/assert/assert.go

- :recycle: .Equalメソッドでレスポンスをassertできるようにした
- :recycle: pids -> ps
- :art: make roomRepo and streamer global
- :recycle: extract connectToWs
- :recycle: WriteWsRequest for test

refactor ws test

---

docs/openapi/v1.yml
integration/ws/ws_test.go
internal/domain/event.go
internal/domain/player.go
internal/domain/rail.go
internal/oapi/constructor.go
internal/oapi/converter.go
internal/oapi/oapi_models.go
internal/usecases/services/ws/wshandler/block.go
internal/usecases/services/ws/wshandler/card.go

🔥 Id To Index

---

docs/openapi/v1.yml
integration/ws/testutils_test.go
integration/ws/ws_test.go
internal/domain/room.go
internal/handler/handler.go
internal/oapi/converter.go
internal/oapi/oapi_models.go
internal/oapi/oapi_server.go
internal/usecases/repository/repoimpl/room.go
internal/usecases/services/ws/streamer.go
internal/usecases/services/ws/wshandler/card.go
internal/usecases/services/ws/wshandler/gamestart.go
pkg/optional/optional.go
pkg/sync/slice.go

- :fire: remove room api
- :boom: change GET /ws parameters

:boom: ws接続時に部屋を作成or参加させるようにする
